### ISSUE TITLE
Estilo de exibição diferente

### ISSUE THREAD

**Issue by jos3s** [maykbrito/simple-webview#2]
Há algum motivo especifico para o aplicativo ficar desse jeito? Tipo com os menus, diferente do mostrado no seu vídeo.
![image](https://user-images.githubusercontent.com/50359547/81849777-68a60880-952d-11ea-9b6d-1323b1b0546c.png)

Há algum meio do aplicativo ficar ouvindo live server do vs code? Tipo se eu abrir um index  diferente com o aplicativo já aberto e ele trocar automaticamente para essa novo arquivo?

Foram isso, é um aplicativo muito bom

**Comment by apsampaio** [comment]
Acho que você deveria trocar a porta, o live server funciona na porta 5500, tente alterar no arquivo config.js
