### ISSUE TITLE
Altura e largura não respeitados

### ISSUE THREAD

**Issue by jos3s** [maykbrito/simple-webview#3]
Essas configurações deveriam definir o tamanho da janela do aplicativo, não é? Estou enfrentando um problema alterando a altura e largura nas configurações o aplicativo não respeita esses dados, há alguma maneira de corrigir isso?

![image](https://user-images.githubusercontent.com/50359547/81850279-24673800-952e-11ea-9c3b-e0c3c250a91c.png)

**Comment by SouzaLuiz** [comment]
Não sei se já resolveu seu problema, mas a largura e altura nesse config.js tem que ser sem as aspas, estando sem aspas o app respeita. :point_down:
```js
module.exports = {
   wifth: 500,
   heigth: 400,
   url: "http://localhost:3000/"
}
```

**Comment by jos3s** [comment]
> Não sei se já resolveu seu problema, mas a largura e altura nesse config.js tem que ser sem as aspas, estando sem aspas o app respeita. 
> 
> ```js
> module.exports = {
>    wifth: 500,
>    heigth: 400,
>    url: "http://localhost:3000/"
> }
> ```

Vou tentar isso depois, valeu pela ajuda
